#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : packaging
Version  : 20.4
Release  : 41
URL      : https://files.pythonhosted.org/packages/55/fd/fc1aca9cf51ed2f2c11748fa797370027babd82f87829c7a8e6dbe720145/packaging-20.4.tar.gz
Source0  : https://files.pythonhosted.org/packages/55/fd/fc1aca9cf51ed2f2c11748fa797370027babd82f87829c7a8e6dbe720145/packaging-20.4.tar.gz
Summary  : Core utilities for Python packages
Group    : Development/Tools
License  : Apache-2.0 BSD-2-Clause
Requires: packaging-license = %{version}-%{release}
Requires: packaging-python = %{version}-%{release}
Requires: packaging-python3 = %{version}-%{release}
Requires: pyparsing
Requires: six
BuildRequires : buildreq-distutils3
BuildRequires : pyparsing
BuildRequires : six

%description
=========
        
        Core utilities for Python packages.

%package license
Summary: license components for the packaging package.
Group: Default

%description license
license components for the packaging package.


%package python
Summary: python components for the packaging package.
Group: Default
Requires: packaging-python3 = %{version}-%{release}

%description python
python components for the packaging package.


%package python3
Summary: python3 components for the packaging package.
Group: Default
Requires: python3-core
Provides: pypi(packaging)
Requires: pypi(pyparsing)
Requires: pypi(six)

%description python3
python3 components for the packaging package.


%prep
%setup -q -n packaging-20.4
cd %{_builddir}/packaging-20.4

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1589909709
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$FFLAGS -fno-lto "
export FFLAGS="$FFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/packaging
cp %{_builddir}/packaging-20.4/LICENSE.APACHE %{buildroot}/usr/share/package-licenses/packaging/598f87f072f66e2269dd6919292b2934dbb20492
cp %{_builddir}/packaging-20.4/LICENSE.BSD %{buildroot}/usr/share/package-licenses/packaging/fdc0e4eabc45522b079deff7d03d70528d775dc0
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/packaging/598f87f072f66e2269dd6919292b2934dbb20492
/usr/share/package-licenses/packaging/fdc0e4eabc45522b079deff7d03d70528d775dc0

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
