#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : packaging
Version  : 20.0
Release  : 37
URL      : https://files.pythonhosted.org/packages/c7/cf/d84b72480a556d9bd4a191a91b0a8ea71cb48e6f6132f12d9d365c51bdb6/packaging-20.0.tar.gz
Source0  : https://files.pythonhosted.org/packages/c7/cf/d84b72480a556d9bd4a191a91b0a8ea71cb48e6f6132f12d9d365c51bdb6/packaging-20.0.tar.gz
Summary  : Core utilities for Python packages
Group    : Development/Tools
License  : Apache-2.0 BSD-2-Clause
Requires: packaging-license = %{version}-%{release}
Requires: packaging-python = %{version}-%{release}
Requires: packaging-python3 = %{version}-%{release}
Requires: pyparsing
Requires: six
BuildRequires : buildreq-distutils3
BuildRequires : pluggy
BuildRequires : py-python
BuildRequires : pyparsing
BuildRequires : pytest
BuildRequires : six
BuildRequires : tox
BuildRequires : virtualenv

%description
packaging
=========
Core utilities for Python packages.
The ``packaging`` project includes the following: version handling, specifiers,
markers, requirements, tags, utilities.

%package license
Summary: license components for the packaging package.
Group: Default

%description license
license components for the packaging package.


%package python
Summary: python components for the packaging package.
Group: Default
Requires: packaging-python3 = %{version}-%{release}

%description python
python components for the packaging package.


%package python3
Summary: python3 components for the packaging package.
Group: Default
Requires: python3-core

%description python3
python3 components for the packaging package.


%prep
%setup -q -n packaging-20.0
cd %{_builddir}/packaging-20.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1578326359
# -Werror is for werrorists
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$CFLAGS -fno-lto "
export FFLAGS="$CFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/packaging
cp %{_builddir}/packaging-20.0/LICENSE.APACHE %{buildroot}/usr/share/package-licenses/packaging/598f87f072f66e2269dd6919292b2934dbb20492
cp %{_builddir}/packaging-20.0/LICENSE.BSD %{buildroot}/usr/share/package-licenses/packaging/fdc0e4eabc45522b079deff7d03d70528d775dc0
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/packaging/598f87f072f66e2269dd6919292b2934dbb20492
/usr/share/package-licenses/packaging/fdc0e4eabc45522b079deff7d03d70528d775dc0

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
